// src/frontend/vue/components/SortCard.vue
<script setup lang="ts">
import { ref } from "vue";

const sortResult = ref<{
  size: number;
  min: number;
  max: number;
  median: number;
  duration: number;
} | null>(null);
const sortLoading = ref(false);

function runSort() {
  sortLoading.value = true;
  const worker = new Worker(
    new URL("../../workers/sort.worker.ts", import.meta.url),
    { type: "module" },
  );
  worker.onmessage = (
    event: MessageEvent<{
      size: number;
      min: number;
      max: number;
      median: number;
      duration: number;
    }>,
  ) => {
    sortResult.value = event.data;
    sortLoading.value = false;
    worker.terminate();
  };
  worker.postMessage({ size: 1000000 });
}
</script>

<template>
  <div class="worker-card">
    <div class="card-title">Sort Array</div>
    <p class="card-desc">Data processing without blocking the UI.</p>
    <button
      @click="runSort"
      :class="{ loading: sortLoading }"
      :disabled="sortLoading"
    >
      {{ sortLoading ? "Sorting" : "Sort 1M Numbers" }}
    </button>
    <div class="worker-result">
      <div class="result-row">
        <span>Min</span
        ><span>{{
          sortResult ? sortResult.min.toLocaleString() : "\u2014"
        }}</span>
      </div>
      <div class="result-row">
        <span>Max</span
        ><span>{{
          sortResult ? sortResult.max.toLocaleString() : "\u2014"
        }}</span>
      </div>
      <div class="result-row">
        <span>Median</span
        ><span>{{
          sortResult ? sortResult.median.toLocaleString() : "\u2014"
        }}</span>
      </div>
      <div class="result-row">
        <span>Duration</span
        ><span>{{ sortResult ? `${sortResult.duration}ms` : "\u2014" }}</span>
      </div>
    </div>
  </div>
</template>

// src/frontend/react/components/SortCard.tsx
import { useCallback, useState } from "react";

type SortResult = {
  size: number;
  min: number;
  max: number;
  median: number;
  duration: number;
};

export const SortCard = () => {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<SortResult | null>(null);

  const runSort = useCallback(() => {
    setLoading(true);
    const worker = new Worker(
      new URL("../../workers/sort.worker.ts", import.meta.url),
      { type: "module" },
    );
    worker.onmessage = (event: MessageEvent<SortResult>) => {
      setResult(event.data);
      setLoading(false);
      worker.terminate();
    };
    worker.postMessage({ size: 1000000 });
  }, []);

  return (
    <div className="worker-card">
      <div className="card-title">Sort Array</div>
      <p className="card-desc">Data processing without blocking the UI.</p>
      <button
        className={loading ? "loading" : ""}
        disabled={loading}
        onClick={runSort}
      >
        {loading ? "Sorting" : "Sort 1M Numbers"}
      </button>
      <div className="worker-result">
        <div className="result-row">
          <span>Min</span>
          <span>{result ? result.min.toLocaleString() : "\u2014"}</span>
        </div>
        <div className="result-row">
          <span>Max</span>
          <span>{result ? result.max.toLocaleString() : "\u2014"}</span>
        </div>
        <div className="result-row">
          <span>Median</span>
          <span>{result ? result.median.toLocaleString() : "\u2014"}</span>
        </div>
        <div className="result-row">
          <span>Duration</span>
          <span>{result ? `${result.duration}ms` : "\u2014"}</span>
        </div>
      </div>
    </div>
  );
};
